name: sphinx
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13.*
  - sphinx=8.2.3
  - alabaster
  - apeye
  - apeye-core
  - archspec
  - attrs
  - autodocsumm
  - babel
  - beautifulsoup4
  - bleach
  - boltons
  - brotli
  - cachecontrol
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - cssutils
  - defusedxml
  - dict2css
  - distro
  - docutils
  - entrypoints
  - python-fastjsonschema
  - filelock
  - frozendict
  - furo
  - html5lib
  - idna
  - imagesize
  - importlib-metadata
  - importlib-resources
  - jinja2
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jupyter_client
  - jupyter_core
  - jupyterlab_pygments
  - lockfile
  - markdown-it-py
  - markupsafe
  - mdit-py-plugins
  - mdurl
  - mistune
  - msgpack-python
  - mypy_extensions
  - myst-parser
  - natsort
  - nbclient
  - nbconvert
  - nbformat
  - packaging
  - pandocfilters
  - pip
  - platformdirs
  - pluggy
  - pycosat
  - pycparser
  - pygments
  - pysocks
  - python-dateutil
  - python
  - pytz
  - pyyaml
  - pyzmq
  - referencing
  - requests
  - rpds-py
  - ruamel.yaml
  - ruamel.yaml.clib
  - setuptools
  - six
  - snowballstemmer
  - soupsieve
  - sphinx-autodoc-typehints
  - sphinx-basic-ng
  - sphinx-inline-tabs
  - sphinx-jinja2-compat
  - sphinx-notfound-page
  - sphinx-prompt
  - sphinx-reredirects
  - sphinx-tabs
  - sphinx-toolbox
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-googleanalytics
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-video
  - sphinxcontrib-youtube
  - tabulate
  - tinycss2
  - tornado
  - tqdm
  - traitlets
  - truststore
  - typing_extensions
  - urllib3
  - webencodings
  - wheel
  - zipp
  - zstandard